import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/theme/ThemeContext";
import { AuthProvider } from "@/context/AuthContext";
import { PaymentProvider } from '@/context/PaymentContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "I Am Barley",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Wrap your app. It might look slightly different depending on your setup */}
        <ThemeProvider>
          <AuthProvider>
            <PaymentProvider> 
              <Navbar />
              {children}
            </PaymentProvider> 
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}